#!/bin/bash

# Bash Functions Setup
# - Generate cc<project> launcher functions for each repo in ~/code/
# - Add to ~/.bashrc with deduplication

# Note: Don't use 'set -e' - arithmetic (( )) can return 1 when incrementing from 0

# Color codes
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

# Markers for .bashrc block
MARKER_START="# >>> JAT Claude Launchers >>>"
MARKER_END="# <<< JAT Claude Launchers <<<"

echo -e "${BLUE}Setting up bash launcher functions...${NC}"
echo ""

# Scan ~/code/ for projects
CODE_DIR="$HOME/code"

if [ ! -d "$CODE_DIR" ]; then
    echo -e "${YELLOW}⚠ ~/code/ directory not found${NC}"
    exit 0
fi

# Build the function block
FUNCTIONS_BLOCK="$MARKER_START
# Auto-generated by JAT installer
# Launch Claude Code with /jat:start for each project

"

REPOS_FOUND=0

for repo_dir in "$CODE_DIR"/*; do
    # Skip if not a directory
    if [ ! -d "$repo_dir" ]; then
        continue
    fi

    # Skip if not a git repository
    if [ ! -d "$repo_dir/.git" ]; then
        continue
    fi

    REPO_NAME=$(basename "$repo_dir")

    # Create function name: jat- + repo name (lowercase)
    # e.g., jat -> jat-jat, my-project -> jat-myproject
    FUNC_NAME="jat-$(echo "$REPO_NAME" | tr '[:upper:]' '[:lower:]' | tr -d '-')"

    echo -e "  ${GREEN}✓${NC} $FUNC_NAME() -> ~/code/$REPO_NAME"

    FUNCTIONS_BLOCK+="$FUNC_NAME() {
    (cd ~/code/$REPO_NAME && AGENT_MAIL_URL=\"http://localhost:8765\" claude --dangerously-skip-permissions \"/jat:start\" \"\$@\")
}

"
    REPOS_FOUND=$((REPOS_FOUND + 1))
done

FUNCTIONS_BLOCK+="$MARKER_END"

if [ $REPOS_FOUND -eq 0 ]; then
    echo -e "${YELLOW}⚠ No git repositories found in ~/code/${NC}"
    exit 0
fi

echo ""

# Update ~/.bashrc
BASHRC="$HOME/.bashrc"

if [ ! -f "$BASHRC" ]; then
    echo -e "${YELLOW}⚠ ~/.bashrc not found, creating...${NC}"
    touch "$BASHRC"
fi

# Remove existing JAT block if present
if grep -q "$MARKER_START" "$BASHRC"; then
    echo "  → Removing existing JAT launcher block..."
    # Use sed to remove the block between markers (inclusive)
    sed -i "/$MARKER_START/,/$MARKER_END/d" "$BASHRC"
fi

# Append new block
echo "  → Adding launcher functions to ~/.bashrc..."
echo "" >> "$BASHRC"
echo "$FUNCTIONS_BLOCK" >> "$BASHRC"

echo ""
echo -e "${GREEN}=========================================${NC}"
echo -e "${GREEN}Bash Functions Setup Complete${NC}"
echo -e "${GREEN}=========================================${NC}"
echo ""
echo "  Functions added: $REPOS_FOUND"
echo "  Location: ~/.bashrc"
echo ""
echo "  To use now, run:"
echo "    source ~/.bashrc"
echo ""
echo "  Then launch any project with:"
for repo_dir in "$CODE_DIR"/*; do
    if [ -d "$repo_dir" ] && [ -d "$repo_dir/.git" ]; then
        REPO_NAME=$(basename "$repo_dir")
        FUNC_NAME="jat-$(echo "$REPO_NAME" | tr '[:upper:]' '[:lower:]' | tr -d '-')"
        echo "    $FUNC_NAME"
    fi
done | head -5
echo "    ..."
echo ""
